### ISSUE TITLE
cant create lightsheet   (error with Create_lightsheet.py)

### ISSUE THREAD

**Issue by CreeperChopper** [markus-ebke/Blender-Lightsheet#1]
![image](https://user-images.githubusercontent.com/90483734/186557354-7ee030a0-28f5-47b8-9974-06ac7cb530ac.png)

here is the error

**Comment by markus-ebke** [comment]
Thanks for letting me know. Blender 3.0 changed the bmesh.ops.create_icosphere keyword "diameter" to "radius" and I didn't notice it before. I fixed it now, please have a look at the new release v1.2.
